### ISSUE TITLE
Dagger and rocks on inventory

### ISSUE THREAD

**Issue by Wkymys** [PhantasarProductions/cynthia#55]
If you finish a level with a dagger or a rock on inventory, they will appear on the inventory on the next level (but not usable).

**Comment by Tricky1975** [comment]
Thank you for telling me this. 
Since I only played one puzzle each time I ran the game (which is not that strange during development tests) this was an easy bug for me to miss. I shall try to fix this one tonight (In Dutch local time I mean) ;)

**Comment by Tricky1975** [comment]
Fixed! 
The version with this fix will appear on itch.io soon. On Game Jolt I shall update the game once I took care of a few more issues or at the end of this week
